### ISSUE TITLE
"future" package not installing

### ISSUE THREAD

**Issue by xlScarfacelx** [mav-rik/facerestore_cf#14]
It seems like I´m encountering an issue with the future package during the installation process. The error indicates that there is a problem with the future package's setup script. Tried installing "future" seperatly and diferent versions (0.18.2 and 0.18.1).What else can i do?

C:\Users\gdias\OneDrive\Documentos\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf>echo This will install cv2 for the windows portable version of ComfyUI
This will install cv2 for the windows portable version of ComfyUI

C:\Users\gdias\OneDrive\Documentos\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf>..\..\..\python_embeded\python.exe -s -m pip install -r requirements.txt
Requirement already satisfied: opencv-python in c:\users\gdias\onedrive\documentos\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (4.9.0.80)
Requirement already satisfied: numpy in c:\users\gdias\onedrive\documentos\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 2)) (1.26.2)
Requirement already satisfied: torch in c:\users\gdias\onedrive\documentos\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 3)) (2.1.2+cu121)
Requirement already satisfied: torchvision in c:\users\gdias\onedrive\documentos\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 4)) (0.16.2+cu121)
Requirement already satisfied: addict in c:\users\gdias\onedrive\documentos\comfyui_windows_portable\python_embeded\lib\site-packages (from -r requirements.txt (line 5)) (2.4.0)
Collecting future (from -r requirements.txt (line 6))
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\gdias\AppData\Local\Temp\pip-install-nl78dj2k\future_51effea58ea5475d92b32373cf677e32\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by sachin-detrax** [comment]
same issue

**Comment by willyRed77** [comment]
Im installed with python from the folder python_embeded with python.exe, for install in the venv of ComfyUI, i added this flag when installing manually.
The flag in question is: [--use-pep517](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-use-pep517)

**Comment by xlScarfacelx** [comment]
> Im installed with python from the folder python_embeded with python.exe, for install in the venv of ComfyUI, i added this flag when installing The flag in question is: [--use-pep517](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-use-pep517) I hope you achieve @xlScarfacelx

Thank you so so much, i have been trying to solve this for weeks. it work perfevtly

**Comment by Batoune** [comment]
Hey, I got the same issue and I don't know that the "venv of ComfyUI" is. Never used python. Could you please tell me what to do exactly ? 

I tried to use this command from the python.exe, but it doesn't work : 
> subprocess.run([r"..\ComfyUI\custom_nodes\facerestore_cf\embedded_install.bat"]) --use-pep517

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'use' is not defined

Thank you !

**Comment by willyRed77** [comment]
> Hey, I got the same issue and I don't know that the "venv of ComfyUI" is. Never used python. Could you please tell me what to do exactly ?
> 
> I tried to use this command from the python.exe, but it doesn't work :
> 
> > subprocess.run([r"..\ComfyUI\custom_nodes\facerestore_cf\embedded_install.bat"]) --use-pep517
> 
> Traceback (most recent call last): File "", line 1, in NameError: name 'use' is not defined
> 
> Thank you !

The promblem in question, its when installing future... so the next command will help you installing it. 
`.\python_embeded\python.exe -m pip install future --use-pep517`
