### ISSUE TITLE
ModuleNotFoundError with FaceRestoreHelper

### ISSUE THREAD

**Issue by colintemp** [mav-rik/facerestore_cf#15]
I'm struggling to install this facerestore_cf custom node. When I start ComfyUI I get this error message:
`Traceback (most recent call last):
  File "C:\Users\me\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\me\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 8, in <module>
    from custom_nodes.facerestore_cf.facelib.utils.face_restoration_helper import FaceRestoreHelper
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

Cannot import C:\Users\me\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: No module named 'custom_nodes.facerestore_cf'`

I've tried installing via the Manager as well as manually, and uninstalling and reinstalling. Also tried updating, but no joy. What am I doing wrong?

**Comment by colintemp** [comment]
Turns out it was my own fault. I ran update_comfyui_and_python_dependencies.bat from the ComfyUI_windows_portable\update folder and it seems to have fixed some dependencies. After tha,t this node ran fine when I restarted Comfyui.
