### ISSUE TITLE
No module named 'custom_nodes.facerestore_cf' (ComfyUI Desktop)

### ISSUE THREAD

**Issue by Ryxx** [mav-rik/facerestore_cf#29]
Hello,

I'm using ComfyUI Desktop version. By default, it installs itself in Appdata.

I noticed that if I git clone Facerestore_CF inside the following folder, it works correctly:
"C:\Users\Utilisateur\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\custom_nodes"

But I chose to have another location for my "user" folders (.venv, custom_nodes, input, models, output, user, uv-cache). For example, mine is in:
"L:\COMFY UI\ComfyUI\custom_nodes"

And I'm getting this error:

```
Traceback (most recent call last):
  File "C:\Users\Utilisateur\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "L:\COMFY UI\ComfyUI\custom_nodes/facerestore_cf\__init__.py", line 8, in <module>
    from custom_nodes.facerestore_cf.facelib.utils.face_restoration_helper import FaceRestoreHelper
ModuleNotFoundError: No module named 'custom_nodes.facerestore_cf'

Cannot import L:\COMFY UI\ComfyUI\custom_nodes/facerestore_cf module for custom nodes: No module named 'custom_nodes.facerestore_cf'
```
I guess the code doesn't handle the user's custom paths.
Would be it possible to update that part, so I can put it with the rest of the custom_nodes (and avoid putting anything in Appdata)?

Thanks.

**Comment by FansuTen** [comment]
I have the same problem. Check your facerestore_cf folder name.  Make sure it is 'facerestore_cf' (not facerestore_cf-master or others).

**Comment by ww9699999** [comment]
Have you solved this problem?

**Comment by FansuTen** [comment]
Yes, I did. Just change the folder name 'facerestore_cf-master' to 'facerestore_cf'.
I checked the __init__.py, found 'from custom_nodes.facerestore_cf.facelib.utils.face_restoration_helper import FaceRestoreHelper', I thought that 'custom_nodes.facerestore_cf' maybe means the path 'custom_nodes/facerestore_cf'.

**Comment by polarNerd204** [comment]
YUP folder was named wrong .....wierd.
ALSO Thanks

**Comment by mav-rik** [comment]
A PR that fixes this issue is merged
